import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

const titleFont = Inter({
  variable: "--font-title",
  subsets: ["latin"],
});

const bodyFont = Roboto({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titleFont.variable} ${bodyFont.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
